"""Generate tests for converted Prefect flows."""

from typing import Any


def generate_flow_tests(
    dag_info: dict[str, Any],
    flow_name: str,
    task_mapping: dict[str, str],
) -> str:
    """Generate pytest tests for a converted flow.
    
    Args:
        dag_info: Parsed DAG information
        flow_name: Name of the converted flow function
        task_mapping: Mapping of original task IDs to new function names
        
    Returns:
        Python code for test file
    """
    dag_id = dag_info.get("dag_id", "converted_flow")
    module_name = flow_name  # Assumes flow is in {flow_name}.py
    
    lines = [
        '"""Tests for converted Prefect flow: {dag_id}',
        '',
        'These tests verify the migration from Airflow DAG to Prefect flow.',
        'Run with: pytest {test_file}',
        '',
        '✨ Generated by airflow-unfactor',
        '"""',
        '',
        'import pytest',
        'from prefect import flow',
        'from prefect.testing.utilities import prefect_test_harness',
        '',
        f'from {module_name} import {flow_name}',
    ]
    
    # Import individual tasks
    if task_mapping:
        task_imports = ', '.join(task_mapping.values())
        lines.append(f'from {module_name} import {task_imports}')
    
    lines.extend([
        '',
        '',
        '# ✨ Prefect Advantage: Easy Testing',
        '# Unlike Airflow where testing requires mocking the entire execution context,',
        '# Prefect tasks are just Python functions - test them directly!',
        '',
        '',
        '@pytest.fixture(scope="module")',
        'def prefect_harness():',
        '    """Set up Prefect test harness for flow execution."""',
        '    with prefect_test_harness():',
        '        yield',
        '',
    ])
    
    # Generate individual task tests
    lines.append('')
    lines.append('# === Task Tests ===')
    lines.append('# Test each task independently to verify conversion')
    lines.append('')
    
    for original_id, func_name in task_mapping.items():
        lines.extend([
            '',
            f'class Test{func_name.title().replace("_", "")}:',
            f'    """Tests for {func_name} (converted from {original_id})."""',
            '',
            f'    def test_{func_name}_returns_value(self):',
            f'        """Verify {func_name} executes and returns a value."""',
            f'        # Call the task function directly (not as a Prefect task)',
            f'        result = {func_name}.fn()',
            f'        ',
            f'        # TODO: Add specific assertions based on expected behavior',
            f'        # This is a smoke test to verify the function runs',
            f'        assert result is not None or result is None  # Adjust based on expected return',
            '',
            f'    def test_{func_name}_as_task(self, prefect_harness):',
            f'        """Verify {func_name} works as a Prefect task."""',
            f'        # Run as a Prefect task to verify decorator behavior',
            f'        result = {func_name}()',
            f'        ',
            f'        # Prefect tasks return PrefectFuture in some contexts',
            f'        # but in sync context they return the value directly',
            f'        assert True  # Task executed without error',
            '',
        ])
    
    # Generate flow test
    lines.extend([
        '',
        '# === Flow Tests ===',
        '# Test the complete flow execution',
        '',
        '',
        f'class Test{flow_name.title().replace("_", "")}Flow:',
        f'    """Tests for the complete {flow_name} flow."""',
        '',
        f'    def test_flow_executes(self, prefect_harness):',
        f'        """Verify the entire flow runs without errors."""',
        f'        # Run the flow',
        f'        result = {flow_name}()',
        f'        ',
        f'        # Flow completed successfully',
        f'        assert True',
        '',
        f'    def test_flow_task_order(self, prefect_harness):',
        f'        """Verify tasks execute in the correct order."""',
        f'        # TODO: Add assertions about task execution order',
        f'        # This may require inspecting flow run results',
        f'        result = {flow_name}()',
        f'        assert True',
        '',
    ])
    
    # Add migration verification section
    lines.extend([
        '',
        '# === Migration Verification ===',
        '# These tests help verify the migration maintains expected behavior',
        '',
        '',
        'class TestMigrationVerification:',
        '    """Verify the migration from Airflow DAG to Prefect flow."""',
        '',
        '    def test_task_count_matches(self):',
        f'        """Verify we have the expected number of tasks."""',
        f'        expected_tasks = {len(task_mapping)}',
        f'        # Count tasks in the flow',
        f'        # Note: In Prefect, tasks are functions, not objects in a DAG',
        f'        assert expected_tasks == {len(task_mapping)}',
        '',
        '    def test_no_xcom_references(self):',
        '        """Verify no XCom references remain in the converted code."""',
        f'        import inspect',
        f'        source = inspect.getsource({flow_name})',
        f'        assert "xcom_push" not in source',
        f'        assert "xcom_pull" not in source',
        '',
    ])
    
    # Format with proper substitutions
    test_code = '\n'.join(lines)
    test_code = test_code.format(
        dag_id=dag_id,
        test_file=f'test_{module_name}.py',
    )
    
    return test_code


def generate_test_filename(dag_id: str) -> str:
    """Generate test filename from DAG ID."""
    safe_name = dag_id.replace("-", "_").replace(" ", "_").lower()
    return f"test_{safe_name}_flow.py"
