#!/usr/bin/env python3
"""Generate operator coverage documentation from the registry.

This script reads the operator mappings from provider_mappings.py and generates
a searchable markdown documentation file showing:
- All supported operators with their Prefect equivalents
- Status indicators (supported, partial, needs review)
- Required packages and configuration notes
"""

import sys
from pathlib import Path

# Add src to path for import
sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from airflow_unfactor.converters.provider_mappings import (
    OPERATOR_MAPPINGS,
    get_operators_by_category,
)


def generate_operator_coverage_doc() -> str:
    """Generate the operator coverage markdown documentation."""
    lines = [
        "# Airflow Operator Coverage Matrix",
        "",
        "This document lists all Airflow operators supported by airflow-unfactor and their",
        "Prefect equivalents. Generated automatically from the operator registry.",
        "",
        "## Quick Reference",
        "",
        "| Status | Meaning |",
        "|--------|---------|",
        "| ✅ Supported | Full conversion with Prefect integration |",
        "| 🔧 Scaffold | Generates working scaffold code |",
        "| ⚠️ Manual | Requires manual review after conversion |",
        "",
        f"**Total Operators Supported: {len(OPERATOR_MAPPINGS)}**",
        "",
    ]

    categories = get_operators_by_category()
    category_display_names = {
        "aws_s3": "AWS S3",
        "aws_compute": "AWS Compute",
        "aws_data": "AWS Data",
        "gcp_storage": "GCP Storage & BigQuery",
        "gcp_compute": "GCP Compute",
        "gcp_messaging": "GCP Messaging",
        "azure": "Azure",
        "databricks": "Databricks",
        "dbt": "dbt",
        "database": "Database",
        "notifications": "Notifications",
        "http": "HTTP & General",
    }

    for category_key, operators in categories.items():
        display_name = category_display_names.get(category_key, category_key.title())
        lines.append(f"## {display_name}")
        lines.append("")
        lines.append("| Airflow Operator | Prefect Function | Integration | Status |")
        lines.append("|------------------|------------------|-------------|--------|")

        for op_name in operators:
            mapping = OPERATOR_MAPPINGS.get(op_name)
            if mapping:
                integration = mapping.prefect_integration or "stdlib"
                status = "✅ Supported"
                if "TODO" in mapping.code_template:
                    status = "🔧 Scaffold"
                if mapping.notes and ("manual" in mapping.notes.lower() or "review" in mapping.notes.lower()):
                    status = "⚠️ Manual"

                lines.append(f"| `{op_name}` | `{mapping.prefect_function}` | {integration} | {status} |")

        lines.append("")

    # Add package reference section
    lines.extend([
        "## Required Packages",
        "",
        "Below are the Prefect integration packages required for each provider:",
        "",
        "| Provider | Package | Installation |",
        "|----------|---------|--------------|",
        "| AWS | prefect-aws | `pip install prefect-aws` |",
        "| GCP | prefect-gcp | `pip install prefect-gcp` |",
        "| Azure | prefect-azure | `pip install prefect-azure` |",
        "| Databricks | prefect-databricks | `pip install prefect-databricks` |",
        "| dbt | prefect-dbt | `pip install prefect-dbt` |",
        "| Snowflake | prefect-snowflake | `pip install prefect-snowflake` |",
        "| SQL | prefect-sqlalchemy | `pip install prefect-sqlalchemy` |",
        "| Slack | prefect-slack | `pip install prefect-slack` |",
        "| Email | prefect-email | `pip install prefect-email` |",
        "| Kubernetes | prefect-kubernetes | `pip install prefect-kubernetes` |",
        "",
        "## Adding New Operators",
        "",
        "To add support for a new Airflow operator:",
        "",
        "1. Add an `OperatorMapping` entry to `src/airflow_unfactor/converters/provider_mappings.py`",
        "2. Add the operator to the appropriate category in `get_operators_by_category()`",
        "3. Add tests in `tests/test_provider_operators.py`",
        "4. Run `python scripts/generate_operator_docs.py` to regenerate this file",
        "",
        "---",
        "",
        "*Generated by airflow-unfactor*",
    ])

    return "\n".join(lines)


def main():
    """Generate and write the operator coverage documentation."""
    docs_dir = Path(__file__).parent.parent / "docs"
    docs_dir.mkdir(exist_ok=True)

    output_path = docs_dir / "operator-coverage.md"
    content = generate_operator_coverage_doc()

    output_path.write_text(content)
    print(f"Generated {output_path}")
    print(f"Total operators documented: {len(OPERATOR_MAPPINGS)}")


if __name__ == "__main__":
    main()
